#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_date = "2024-05-02"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "comment"
database_id = "218baf47-5600-4e70-b5bf-79dffbac9680"

[vars]
IS_CLOUDFLARE_WORKER = "true"

[dev]
port = 5000
