#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_date = "2024-05-02"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "b35e0bd5-6d17-42eb-a597-ff4869a74461"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.mingy.org"

[dev]
port = 5000
